### ISSUE TITLE
Demultiplexing Confusion

### ISSUE THREAD

**Issue by ghost** [fls-bioinformatics-core/genomics#4]
Hi,

I ran "demultiplex_undetermined_fastq.py" on Undertermined Indices directory from CASAVA output of a HiSeq 2500 run. I provided the sample sheet as mentioned in instructions. However, the output that I get on demultiplexing is funny. For example, a Lane 4 CTTGTA barcode has following paired reads.

CTTGTA__L004_R1_001.fastq :
@HISEQ:94:C6P9JACYY:4:1101:1912:2248 1:N:0:NNNGTA
GTTTTATCAATGTGAGTTCTTAATTTTCCATTTTGTAGCTCACTCATAACTTCATTGAATGTAATTGTATGTGTCTAATAAACTCTTTAAATGCTAGANNN

CTTGTA__L004_R2_001.fastq :
@HISEQ:94:C6P9JACYY:4:1101:1912:2248 2:N:0:NNNGTA
CCNAATTTAGAAAATCACTTCCCTTTATAACAAAGGGCTTTCAGAAGCTAAATATCAAATGAAATACCTCTAGCATTTAAAGAGTTTATTAGACACATACA

I'm unable to discern how these reads were assigned to this barcode. 
Also, when I run "report_barcodes.py" on these files, I get multiple barcodes! Am I not supposed to get just one barcode i.e. CTTTGTA for this file. 

Please, let me know, how can I solve this issue.

PS: Please fix "report_barcodes.py". It is unable to locate module bcftbx.FASTQFile

**Comment by pjbriggs** [comment]
Appears that reporting user "ghost" has been deleted from github.

I've put the PS (re report_barcodes.py) into a separate issue #5.

**Comment by pjbriggs** [comment]
Looking at this again, I believe that this is an issue with matching `N`s in the barcodes.

The barcode for the two reads in his example can be found at the end of the read header lines (i.e. lines starting `@HISEQ:94...`: for both the barcode is `NNNGTA`, which will match the supplied barcode (`CTTGTA`) if `N`s are deemed to match *any*  base (`C`, `T`, `G` or `A`).

More correct behaviour would be to treat `N` as a mismatch to anything, in which case the reads would only be selected if 3 or more mismatches were allowed.

The current version of `demultiplex_undetermined_fastq.py` doesn't look like it should treat `N`s as matching any base, however I haven't tested this in practice.

The issue with multiple barcodes reported from `report_barcodes.py` seems most likely to be due to the fact that the files do indeed include multiple barcodes (with the `N`s).
