### ISSUE TITLE
Samplesheet does not recognize "Manifests" section

### ISSUE THREAD

**Issue by golharam** [fls-bioinformatics-core/genomics#86]
I have an Illumina sample sheet that has a section called "Manifests".  When I try to read the samplesheet with bcftbx, I get the error 
  File "bcftbx/IlluminaData.py", line 921, in __init__
    self._read_sample_sheet(fp)
  File "bcftbx/IlluminaData.py", line 1022, in _read_sample_sheet
    section)
IlluminaDataError: Unrecognised section 'Manifests': not a valid IEM sample sheet?

However, the Illumina samplesheet spec says this is a valid section. 

https://emea.illumina.com/content/dam/illumina-marketing/documents/products/technotes/sequencing-sheet-format-specifications-technical-note-970-2017-004.pdf

**Comment by golharam** [comment]
My samplesheet looks like this:

[Header],,,,,,,,,
IEMFileVersion,4,,,,,,,,
Investigator Name,Erik,,,,,,,,
Experiment Name,myexp,,,,,,,,
Date,1/19/2019,,,,,,,,
Workflow,GenerateFASTQ,,,,,,,,
Application,FASTQ Only,,,,,,,,
Assay,Nextera XT v2 Set A,,,,,,,,
Description,NGS_test,,,,,,,,
Chemistry,Amplicon,,,,,,,,
,,,,,,,,,
[Manifests],,,,,,,,,
A,,,,,,,,,.AmpliconManifest
,,,,,,,,,
[Reads],,,,,,,,,
151,,,,,,,,,
151,,,,,,,,,
,,,,,,,,,
[Settings],,,,,,,,,
ReverseComplement,0,,,,,,,,
,,,,,,,,,
[Data],,,,,,,,,
...

**Comment by pjbriggs** [comment]
Hello @golharam thanks for the report and the additional information. I haven't come across the `[Manifests]` section before, but I've now made changes in PR #87 which should address the problem with this section not being recognised.

If you're okay to reinstall the code from the `devel` branch then you can try this now; otherwise I'll make a patch version available on GitHub later today.

**Comment by pjbriggs** [comment]
Fix now included in latest release (1.5.4).
